# Generated by Django 2.2.16 on 2023-02-16 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subscriber', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
